{
 "title": "KPI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer Sent Logs / Consumer Accepted Logs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(otelcol_receiver_accepted_log_records{job=\"consumer\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(otelcol_exporter_sent_log_records{job=\"producer\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "kafka_consumer_group_lag", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Sending Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "otelcol_exporter_queue_size{job=\"consumer\", exporter=\"chronicle/secops-http\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "otelcol_exporter_queue_capacity{job=\"consumer\", exporter=\"chronicle/secops-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Log Records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_send_failed_log_records{job=\"consumer\", exporter=\"chronicle/secops-http\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}